# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y

# GPIO for pin configuration
CONFIG_GPIO=y

CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_DCACHE=n
