# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BUFFER_SIZE=4096

CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y

# GPIO for pin configuration
CONFIG_GPIO=y

# Sample configuration
CONFIG_EXMIF_FLASH_TEST_ERASE_ONLY=n
CONFIG_EXMIF_FLASH_TEST_FULL_RANGE=n
